 <form method="post" action="index.php">
                
                    <label for="username">Pseudo</label>
                    <input type="text" name="username" id="username" />
                    
                    <label for="email">email</label>
                    <input type="email" name="email" id="email" />
                    
                    <label for="password">password</label>
                    <input type="password" name="password" id="password" />
                    
                    <label for="confirmPassword">confirmPassword </label>
                    <input type="password" name="confirmPassword" id="confirmPassword" />
                    
                    <input type="submit" value="Envoyer"/>
            </form>