<h2>Accueil</h2>

    <?php 
    foreach($data["category"] as $category){ 
    ?>
    <ul>
        <h3><?= $category->getName() ?></h3>
        
        <?php foreach($data["salon"] as $salon)
        { ?>
            <?php if($category->getName() === $salon->getCategory())
            { ?>
                <li> <?= $salon->getName() ?></li>
            <?php } ?>
            
            ?>
        <?php } ?> 
    </ul>        
    <?php } ?>
    
