<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>discoyep</title>

    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link rel="stylesheet" href="assets/styles/css/style.css">
    <script src="https://kit.fontawesome.com/dbf8b52bf4.js" crossorigin="anonymous"></script>
    
</head>
<body>
    <h1>Distorsion</h1>
    <?php  require  'partials/_header.phtml'; ?>
    <main>
    <?php require "templates/".$template."/".$template.".phtml";?>
    </main>
    <?php  require  'partials/_footer.phtml'; ?>
    <section id="write">
        <form>
            <label for="message">Message :</label>
                <textarea name="message" id="message">

                </textarea>
            <button type="submit">Envoyer</button>
        </form>
</body>
    
    
</html>
