 <form method="post" action="index.php?route=register-post">
                
                    <label for="NomPost">ecrit ton message</label>
                    <input type="text" name="NomPost" id="NomPost" />
                    
                    <label>Choisit un salon</label>
         
                    <select name="salon">
                     <?php 
                          foreach($data as $salon){ 
                          ?>
        <option><?= $salon->getName();
         
        ?></option>
                     <?php } ?>
                    </select>
                    <?php ?>
                    <input type="submit" value="Envoyer"/>
            </form>