
<nav id="nav">
    <ul>
        <li><a href="index.php?route=homepage">Accueil</a></li>
        <li><a href="index.php?route=login">Connexion</a></li>
        <li><a href="index.php?route=register">Création de compte</a></li>
        <li><a href="index.php?route=register-category">Création de categorie</a></li>
        <li><a href="index.php?route=register-salon">Création de salon</a></li>
        <li><a href="index.php?route=register-post">Création de post</a></li>
    </ul>
</nav>
