<section id="nav">
<nav>
    <ul>
        <li><a href="index.php?route=homepage">Accueil</a></li>
        <li><a href="index.php?route=login">Connexion</a></li>
        <li><a href="index.php?route=register">création de compte</a></li>
        <li><a href="index.php?route=register-category">création de categorie</a></li>
        <li><a href="index.php?route=register-salon">création de salon</a></li>
        <li><a href="index.php?route=register-post">création de post</a></li>
    </ul>
</nav>
</section>