 
 <section class="saloon">
  <form method="post" action="index.php?route=register-salon">
                
        <label for="NomSalon">Nom de Salon</label>
        <input type="text" name="NomSalon" id="NomSalon" /><br>
                    

                    <label>Choisit une catégorie</label>
                    <select name="cat">
                     <?php 
                          foreach($data as $category){ ?>
        <option><?= $category->getName()?></option>
                     <?php } ?>
                    </select>
                    <input type="submit" value="Envoyer"/>
            </form>