 <form method="post" action="index.php?route=register-salon">
                
                    <label for="NomSalon">Nom de Salon</label>
                    <input type="text" name="NomSalon" id="NomSalon" />
                    
                    <label for="category">Choisit une catégorie</label>
                    <select name="category" id="category">
                     
                     <option value="Hogwarts">Hogwarts</option>
                    </select>
                    
                    <input type="submit" value="Envoyer"/>
            </form>