 <form method="post" action="index.php">
                
                    <label for="loginEmail">login</label>
                    <input type="email" name="loginEmail" id="loginEmail" />
                    
                    <label for="loginPassword">password</label>
                    <input type="password" name="loginPassword" id="loginPassword" />
                    
                    <input type="submit" value="Envoyer"/>
            </form>