 <form method="post" action="index.php?route=login">
                
                    <label for="email">login</label>
                    <input type="email" name="email" id="email" />
                    
                    <label for="password">password</label>
                    <input type="password" name="password" id="password" />
                    
                    <input type="submit" value="Envoyer"/>
            </form>